from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol
from pathlib import Path
import pandas as pd

from tgapp.domain.models import CorrectionFile, ThermogramFile


@dataclass(slots=True)
class DecodedUpload:
    """DTO: decoded binary upload."""
    filename: str
    content_type: str
    raw_bytes: bytes


# Re-export UploadPayload from dto (used by ports)
from tgapp.application.dto import UploadPayload  # noqa: F401


class SessionRepository(Protocol):
    """Файловое хранилище сессий."""

    def create_session(self) -> str: ...
    def session_dir(self, session_id: str) -> Path: ...
    def ensure(self) -> Path: ...
    def save_thermograms(self, session_id: str, frames: dict[str, pd.DataFrame]) -> list[str]: ...
    def save_raw_thermograms(self, session_id: str, frames: dict[str, pd.DataFrame]) -> list[str]: ...
    def save_frame(self, path: Path, frame: pd.DataFrame) -> Path: ...
    def save_json(self, path: Path, data: dict) -> Path: ...
    def load_thermograms(self, session_id: str) -> dict[str, pd.DataFrame]: ...
    def load_raw_thermograms(self, session_id: str) -> dict[str, pd.DataFrame]: ...
    def load_frame(self, path: Path) -> pd.DataFrame: ...
    def load_json(self, path: Path) -> dict: ...
    def correction_path(self, session_id: str) -> Path: ...
    def metadata_path(self, session_id: str) -> Path: ...
    def processed_path(self, session_id: str) -> Path: ...
    def raw_plot_path(self, session_id: str) -> Path: ...
    def thermogram_dir(self, session_id: str) -> Path: ...
    def settings_path(self, session_id: str) -> Path: ...


class ThermogramParser(Protocol):
    """Парсер термограмм."""

    def parse_thermogram_uploads(self, uploads: list[UploadPayload]) -> list[ThermogramFile]: ...
    def parse_correction_upload(self, upload: UploadPayload) -> CorrectionFile: ...
    def decode_upload(self, upload: UploadPayload) -> DecodedUpload: ...


class SessionArchiveService(Protocol):
    """Сервис архивации/разархивации сессий."""

    def pack_session_directory(self, source: Path, dest: Path) -> Path: ...
    def unpack_session_archive(self, archive_path: Path, dest_dir: Path) -> None: ...


class ProcessingResultRepository(Protocol):
    """Сохранение результатов обработки."""

    def save_frame(self, path: Path, frame: pd.DataFrame) -> Path: ...
    def save_json(self, path: Path, data: dict) -> Path: ...
    def load_frame(self, path: Path) -> pd.DataFrame: ...
    def load_json(self, path: Path) -> dict: ...